# Generated by Django 2.2.6 on 2020-04-02 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200402_2302'),
        ('scholarswork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursefiles',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='accounts.Student'),
        ),
    ]
