# Generated by Django 2.2.6 on 2020-04-02 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200402_2302'),
        ('scholarswork', '0002_coursefiles_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefiles',
            name='file',
            field=models.FileField(upload_to='pqs'),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('file', models.FileField(upload_to='materials')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to='accounts.Student')),
            ],
        ),
    ]
