# Generated by Django 2.2.6 on 2020-04-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarswork', '0003_auto_20200402_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
