# Generated by Django 2.2.6 on 2020-04-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarswork', '0004_material_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(unique=True, upload_to='materials'),
        ),
    ]
