# Generated by Django 2.2.6 on 2020-04-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarswork', '0008_auto_20200403_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
