# Generated by Django 2.2.6 on 2020-04-03 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarswork', '0009_auto_20200403_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['created_at']},
        ),
    ]
