# Generated by Django 2.2.6 on 2020-04-04 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_seller'),
        ('scholarswork', '0010_auto_20200403_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefiles',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to='accounts.Student'),
        ),
        migrations.AlterField(
            model_name='material',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to='accounts.Student'),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='products')),
                ('category', models.CharField(choices=[('PAA', 'Phones and Accessories'), ('WC', "Women's clothing"), ('CAA', 'Computers and Accessories'), ('Food Items', 'Food items')], max_length=50)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accounts.Seller')),
            ],
        ),
    ]
