# Generated by Django 2.2.6 on 2020-04-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarswork', '0011_auto_20200404_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-price']},
        ),
    ]
