# Generated by Django 3.0.4 on 2020-04-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarswork', '0012_auto_20200404_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='negotiable',
            field=models.BooleanField(default=False),
        ),
    ]
