# Generated by Django 2.2.6 on 2020-04-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarswork', '0013_products_negotiable'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='jumbo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Phones and Accessories', 'PAA'), ("Women's clothing", 'WC'), ('Computers and Accessories', 'CAA'), ('Food Items', 'Food items')], max_length=50),
        ),
    ]
