# Generated by Django 2.2.6 on 2020-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200402_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uploads',
            field=models.IntegerField(),
        ),
    ]
