# Generated by Django 2.2.6 on 2020-04-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200403_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uploads',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
