# Generated by Django 2.2.6 on 2020-04-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200403_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uploads',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
