# Generated by Django 2.2.6 on 2020-04-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200403_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='uploads',
            field=models.IntegerField(default=0),
        ),
    ]
