# Generated by Django 2.2.6 on 2020-04-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_seller_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='full_name',
            field=models.CharField(default='Adeleke Fisayo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.CharField(default='Osun', max_length=100),
            preserve_default=False,
        ),
    ]
